apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lichess-api.fullname" . }}-lila
  labels:
    app.kubernetes.io/name: {{ include "lichess-api.name" . }}-lila
spec:
  replicas: {{ .Values.lila.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lichess-api.name" . }}-lila
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "lichess-api.name" . }}-lila
    spec:
      containers:
      - name: lila
        image: {{ .Values.lila.image }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
          {{- range $key, $value := .Values.lila.environment }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        ports:
        - containerPort: 9663
        resources:
          {{- toYaml .Values.lila.resources | nindent 10 }}

