# Global settings
global:
  domain: localhost
  url: http://localhost:8080

# Networking
service:
  type: ClusterIP
  port: 80

# MongoDB configuration
mongodb:
  initReplicaSet: true
  primary:
    readinessProbe:
      exec:
        command: ["mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
  enabled: true
  image: mongo:7.0.28-jammy
  replicaSetName: rs0
  primary:
    replicas: 1
  secondary:
    enabled: true
    replicas: 1

# Redis configuration
redis:
  enabled: true
  image: redis:8.0.3-alpine3.21

# Lichess services configuration
lila_ws:
  enabled: true
  image: slvdub/lila-ws:latest
  pullPolicy: Always
  platform: linux/amd64
  environment:
    CONFIG_FORCE_csrf.origin: ${LILA_URL:-http://localhost:8080}
    CONFIG_FORCE_kamon.enabled: ${ENABLE_MONITORING:-false}
    CONFIG_FORCE_influxdb.hostname: influxdb
    CONFIG_FORCE_influxdb.authentication.token: secret
    CONFIG_FORCE_mongo_uri: mongodb://lila-lichess-api-mongodb:27017/lichess?appName=lila-ws
    CONFIG_FORCE_redis.uri: redis://lila-lichess-api-redis
    CONFIG_FORCE_mongo_timeout: "30s"

lila:
  enabled: true
  replicas: 1
  image: slvdub/lila:latest
  pullPolicy: Always
  platform: linux/amd64
  environment:
    LILA_DOMAIN: ${LILA_DOMAIN:-localhost:8080}
    LILA_URL: ${LILA_URL:-http://localhost:8080}
    MOCK_EMAIL: ${MOCK_EMAIL:-true}
    ENABLE_MONITORING: ${ENABLE_MONITORING:-false}
    ENABLE_RATE_LIMITING: ${ENABLE_RATE_LIMITING:-true}

caddy:
  enabled: true
  image: caddy:2.10.2-alpine
  ports:
    - 8080:80
  environment:
    LILA_DOMAIN: ${LILA_DOMAIN:-localhost:8080}
    LILA_URL: ${LILA_URL:-http://localhost:8080}

fishnet:
  lila_fishnet:
    enabled: true
    replicas: 1
    image: slvdub/lila-fishnet:latest
    pullPolicy: Always
    platform: linux/amd64
    environment:
      REDIS_HOST: lila-lichess-api-redis

  play:
    enabled: true
    image: niklasf/fishnet:2.10.0
    environment:
      ENDPOINT: http://lila_fishnet:9665/fishnet
      MAX_BACKOFF: "5"
      STATS_FILE: /stats.json

  analysis:
    enabled: true
    image: niklasf/fishnet:2.10.0
    environment:
      ENDPOINT: http://lila:9663/fishnet
      MAX_BACKOFF: "5"
      STATS_FILE: /stats.json

service:
  type: ClusterIP
  port: 80

