apiVersion: v1
kind: Service
metadata:
  name: {{ include "lichess-api.fullname" . }}-lila-ws
  labels:
    app.kubernetes.io/name: {{ include "lichess-api.name" . }}-lila-ws
spec:
  type: ClusterIP
  ports:
  - port: 9665
    targetPort: 9665
    name: ws
  selector:
    app.kubernetes.io/name: {{ include "lichess-api.name" . }}-lila-ws

