apiVersion: v1
kind: Service
metadata:
  name: lila-fishnet
spec:
  selector:
    app: lila-fishnet
  ports:
    - protocol: TCP
      port: 80
      targetPort: http  # Changez cela si votre application utilise un autre port

